CREATE TABLE stg_case_document_reference (
  Id bigint IDENTITY(1,1) NOT NULL,
  Case__c nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  Name nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ECM_App_ID__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  File_Name__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  Object_ID__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  Repository__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  Document_Type__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ECM_MS_Doctype_Key__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  Update_ECM_Message__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  Update_ECM_Status__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ECM_Uploaded_By__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  ECM_Uploaded_Date_Time__c nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CreatedDate nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  LastModifiedDate nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  migration_lot nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  record_status nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  record_remark nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  record_lastdatetime datetimeoffset NULL,
  CONSTRAINT PK__stg_case__3214EC074167FE7D PRIMARY KEY (Id)
)