services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    platform: "linux/amd64"
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: "Str0ngP@ssw0rd!"
      ACCEPT_EULA: "Y"
    deploy:
      resources:
        limits:
          memory: 8G
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    platform: "linux/amd64"
    container_name: mssql-tools
    depends_on:
      - mssql
    entrypoint: ["/bin/sh", "-lc", "tail -f /dev/null"]

  
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  mssql_data:
    driver: local
  redis-data:
    driver: local