CREATE TABLE case_transaction (
	active_hop_number int NULL,
	amount_deposit_withdrawal real NULL,
	amount_received_deposit_to_account real NULL,
	amount_withdrawal_deposit real NULL,
	approved_amount_1 real NULL,
	approved_amount_2 real NULL,
	approved_amount_3 real NULL,
	auto_close_case_after_resolved bit NULL,
	deposit_amount real NULL,
	fcr bit NULL,
	fr_required bit NULL,
	fund_transfer_bill_payment_amount real NULL,
	ntb_eligible bit NULL,
	ready_to_print bit NULL,
	sla real NULL,
	status_code int NULL,
	sub_integration_system nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	transfer_amount real NULL,
	visible_on_touch bit NULL,
	suffix_1 nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	suffix_2 nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	suffix_3 nvarchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	closed_date datetimeoffset NULL,
	created_on datetimeoffset NULL,
	modified_on datetimeoffset NULL,
	resolved_date datetimeoffset NULL,
	sla_start_date datetimeoffset NULL,
	sla_target_date datetimeoffset NULL,
	transaction_date datetimeoffset NULL,
	call_number nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contact_person_phone nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contact_person_phone_2 nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	case_id uniqueidentifier NOT NULL,
	created_by_id uniqueidentifier NULL,
	created_by_team_id uniqueidentifier NULL,
	modified_by_id uniqueidentifier NULL,
	owner_id uniqueidentifier NULL,
	team_id uniqueidentifier NULL,
	prompt_pay nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fund_code_1 nvarchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fund_code_2 nvarchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	fund_code_3 nvarchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	rm_id nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	to_ext_2 nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	atm_bank_owner_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cancel_reason_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	carousel_service_tab_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	case_status_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_service_type_matrix_reason_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contact_person_channel_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	conversation_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	correct_recipient_bank_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	data_source_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	grouping_service_point_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	original_problem_channel_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	participant_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	previous_reason_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	priority_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_service_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	pta_segment_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	recipient_bank_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_1_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_2_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_list_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	root_cause_list_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_category_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_tab_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_template_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_template_type_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	severity_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sms_code_completed nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sms_code_in_progress nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sms_code_new nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sms_code_resolution_1 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sms_code_resolution_2 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sms_code_resolved nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_service_tab_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	supported_channel_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	transaction_type_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	transfer_type_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wrong_transfer_type_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contact_person_name nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	message_id nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	correct_bank_recipient_account_no varchar(175) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	inter_bank_recipient_account_no nvarchar(175) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contact_person_email nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	customer_name nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_en nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_line_2_en nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_line_2_th nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_name_ttb_touch_en nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_name_ttb_touch_th nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_th nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	atm_bank_owner_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cancel_reason_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	carousel_service_tab_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	case_status_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_service_type_matrix_reason_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contact_person_channel_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	correct_recipient_bank_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	data_source_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	grouping_service_point_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	original_problem_channel_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	previous_reason_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	priority_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_service_value_en nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_service_value_th nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	pta_segment_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	recipient_bank_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_1_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_2_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_list_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	root_cause_list_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_category_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_tab_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_template_type_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_template_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	severity_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_service_tab_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	supported_channel_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	transaction_type_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	transfer_type_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wrong_transfer_type_value nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cancel_reason_comment nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_owner_reason nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	previous_reason_comment nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_list_comment nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	root_cause_list_comment nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	url_link nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	description nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	biller_provider_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	branch_atm_shop_address_thai nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	branch_atm_shop_location_transaction nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	branch_atm_shop_location_transaction_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	branch_atm_shop_number nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	branch_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	branch_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	call_channel nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	call_duration nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	case_number nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_service_type_matrix_reason_comment nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	closed_by nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	closed_by_team nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	correct_target_account nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	document_id nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	document_type nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ec_id nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ems_tracking nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	end_call nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	external_id nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	integration_system nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_2_en nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	object_id nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	owner_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	parent_case_number nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_number_full_1 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_number_full_2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_number_full_3 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_number_marking_1 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_number_marking_2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_number_marking_3 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_type_code_1 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_type_code_2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_type_code_3 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_type_value_1 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_type_value_2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_type_value_3 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	prompt_pay_transfer_account nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	receiver_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ref_1 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ref_2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ref_3 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	repository_id nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolved_by nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolved_by_team nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_type_matrix_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_type_matrix_type nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sla_status nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	staff_id nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	staff_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	start_call nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_product_type_code_1 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_product_type_code_2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_product_type_code_3 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_product_type_value_1 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_product_type_value_2 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_product_type_value_3 nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	team_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wrong_prompt_pay nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wrong_prompt_pay_transfer_account nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wrong_transfer_account nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	issue_2_th nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	status_change_date datetimeoffset NULL,
	status_change_by_id uniqueidentifier NULL,
	status_change_by_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolved_by_id uniqueidentifier NULL,
	status_change_by_team_id uniqueidentifier NULL,
	status_change_by_team_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	is_stm_locked bit DEFAULT 0 NULL,
	is_hop_locked bit DEFAULT 0 NULL,
	is_owner_locked bit DEFAULT 0 NULL,
	is_migration bit NULL,
	migration_lot nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	closed_by_id uniqueidentifier NULL,
	version bigint DEFAULT 0 NULL,
	resolved_by_team_id uniqueidentifier NULL,
	closed_by_team_id uniqueidentifier NULL,
	total_duration real NULL,
	CONSTRAINT PK__case_tra__A8FF8046D0514BBA PRIMARY KEY (case_id)
);