CREATE TABLE case_transaction_sla_hop (
    case_id uniqueidentifier NULL,
    case_sla_hop_id uniqueidentifier NOT NULL,
    close_by_bu bit NULL,
    created_by_id uniqueidentifier NULL,
    created_on datetimeoffset NULL,
    description nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    effective_duration real NULL,
    end_datetime datetimeoffset NULL,
    hop_number int NULL,
    iteration int NULL,
    modified_by_id uniqueidentifier NULL,
    modified_on datetimeoffset NULL,
    owner_id uniqueidentifier NULL,
    owner_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    service_type_matrix_sla_id uniqueidentifier NULL,
    sla_target real NULL,
    sla_target_date datetimeoffset NULL,
    sms_code_in_progress nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    start_datetime datetimeoffset NULL,
    status_code int NULL,
    team_id uniqueidentifier NULL,
    team_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    total_duration real NULL,
    CONSTRAINT PK__case_tra__30843D384635939F PRIMARY KEY (case_sla_hop_id)
);