#!/bin/sh

echo "Running unit tests before push..."

# Run unittest
./gradlew test

# Check if tests failed
if [ $? -ne 0 ]; then
  echo "Unit tests failed. Push aborted."
  exit 1
fi

echo "All tests passed. Proceeding with push."
exit 0
