CREATE TABLE case_transaction_sla_activity (
	[action] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	actual_duration real NULL,
	cancel_reason_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cancel_reason_comment nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cancel_reason_value nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	case_id uniqueidentifier NULL,
	case_sla_activity_id uniqueidentifier NOT NULL,
	change_owner_reason nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_service_type_matrix_reason nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_service_type_matrix_reason_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_service_type_matrix_reason_comment nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	change_service_type_matrix_reason_value nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_by_id uniqueidentifier NULL,
	created_by_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_on datetimeoffset NULL,
	end_date datetimeoffset NULL,
	hop_number_ref int NULL,
	modified_by_id uniqueidentifier NULL,
	modified_by_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	modified_on datetimeoffset NULL,
	owner_id uniqueidentifier NULL,
	owner_name nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	previous_reason_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	previous_reason_comment nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	previous_reason_value nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_list_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_list_comment nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	resolution_list_value nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	root_cause_list_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	root_cause_list_comment nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	root_cause_list_value nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_type_matrix_code nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	service_type_matrix_iteration int NULL,
	start_date datetimeoffset NULL,
	status_code int NULL,
	team_id uniqueidentifier NULL,
	team_name_en nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	team_name_th nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__case_tra__AC83029F3A898C92 PRIMARY KEY (case_sla_activity_id)
);